"""Agregar campo requisito_legal a Control

Revision ID: 6472ed341901
Revises: b7bd1971eeb0
Create Date: 2025-07-11 06:10:01.458217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6472ed341901'
down_revision: Union[str, None] = 'b7bd1971eeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controles', sa.Column('requisito_legal', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controles', 'requisito_legal')
    # ### end Alembic commands ###
